# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1352, 928)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1300, 926))
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1331, 911))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.VideoContainer = QtWidgets.QWidget(self.layoutWidget)
        self.VideoContainer.setMinimumSize(QtCore.QSize(1300, 800))
        self.VideoContainer.setObjectName("VideoContainer")
        self.videoStream = QtWidgets.QLabel(self.VideoContainer)
        self.videoStream.setGeometry(QtCore.QRect(0, 0, 1331, 1350))
        self.videoStream.setMinimumSize(QtCore.QSize(1300, 800))
        self.videoStream.setText("")
        self.videoStream.setObjectName("videoStream")
        self.verticalLayout.addWidget(self.VideoContainer)
        self.ControlContainer = QtWidgets.QWidget(self.layoutWidget)
        self.ControlContainer.setMaximumSize(QtCore.QSize(16777215, 100))
        self.ControlContainer.setObjectName("ControlContainer")
        self.layoutWidget1 = QtWidgets.QWidget(self.ControlContainer)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 20, 929, 81))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(450, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.startButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 0, 0, 1, 1)
        self.switchcamerabutton = QtWidgets.QPushButton(self.layoutWidget1)
        self.switchcamerabutton.setObjectName("switchcamerabutton")
        self.gridLayout.addWidget(self.switchcamerabutton, 0, 1, 1, 1)
        self.pauseButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.pauseButton.setObjectName("pauseButton")
        self.gridLayout.addWidget(self.pauseButton, 0, 2, 1, 1)
        self.quitButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.quitButton.setObjectName("quitButton")
        self.gridLayout.addWidget(self.quitButton, 2, 0, 1, 3)
        self.verticalLayout.addWidget(self.ControlContainer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.switchcamerabutton.setText(_translate("MainWindow", "Switch camera"))
        self.pauseButton.setText(_translate("MainWindow", "Pause"))
        self.quitButton.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
